spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    lettuce:
      pool:
        max-idle: 20
        min-idle: 2
        max-active: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user-service?Unicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: mysql123

#  application:
#    name: userservice  # eureka的服务名称

# nacos配置
#  cloud:
#    nacos:
#      server-addr: localhost:8848  # nacos服务地址
#      discovery:
#        cluster-name: liupanshui # nacos集群配置
#        namespace: 1b5ba1fd-9b4f-4398-beb3-1389eb951af4 # 命名空间 test环境

#userservice:
#  ribbon:
#    NFLoadBlancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

server:
  port: 8081

mybatis:
  #config-location: classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.lh.userservice.mapper: debug

# eureka客户端服务注册
#eureka:
#  # instance:
#  #  hostname: user
#  client:
#    service-url:   # eureka 地址
#      defaultZone: http://127.0.0.1:8083/eureka
#    fetch-registry: true
#    register-with-eureka: true