spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    lettuce:
      pool:
        max-idle: 20
        min-idle: 2
        max-active: 10
  #  application:
  #    name: orderservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order-service?Unicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: mysql123
# nacos配置
#  cloud:
#    nacos:
#      server-addr: localhost:8848  # nacos服务地址
#      discovery:
#        cluster-name: liupanshui   # nacos集群配置
#        namespace: 20b9e0a7-f774-4566-83d8-e96d716d00b7 # 命名空间 dev环境

# nacos 负载均衡
#orderservice:
#  ribbon:
#    NFLoadBlancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# 服务端口配置
server:
  port: 8080

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志配置

#单个日志配置
#logging:
#  level:
#    com.lh.orderservice.mapper: debug

#多个日志配置（日志组）

# eureka客户端服务注册
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8083/eureka

# ribbon 饥饿加载即懒加载，第一次访问的时候才开始加载，时间有点长
#ribbon:
#  eager-load:
#    enabled: true  #开启饥饿加载
#    clients: orderservice      # 对指定的这个服务饥饿加载
#logging:
#  group:
#    loggrop: com.lh.orderservice.mapper,com.lh.orderservice.clients
#  level:
#    loggrop: trace
#
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full
